### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by copyrighthero** [copyrighthero/MI-449-SS17-740-css-spacing-and-layout-T7bJIb#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://zhaohans-kapm87bvfi5cut7bjib.surge.sh/) and meets the following criteria:

- [x] Demonstrate an understanding of the CSS we've learned so far in the class
- [x] Use Flexbox to create the layout of your page
- [x] Use `margin` and `padding` to create space in and between elements
- [x] Use display `block` and `inline-block` properly
- [x] Have fun and do your best to make it pretty, the result should be something you would show to a future employer

Hello @stuartpearman ,

I've finished this project, I have modified the server side project a lot for the html generation, it now uses flex-box padding margin etc, and linted through htmlhint, could you please verify?

P.S. Site generation using command: node server.js [ -s | --save [ dir [ :ext ] ] ]

Thank you and have a good day!

**Comment by stuartpearman** [comment]
Hey Hansheng, great work with this! I'm super impressed you build a static site generator into your app 👏 

You also demonstrate a good knowledge of CSS :shipit:

Some things I think might help:

- Google has a bit about shadows in their [material design guidelines](https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-object-relationships). Shadows are difficult to do well, but there are resources out there that help 🙂 
- On your nav buttons, putting the transition on the regular state (`a` instead of `a:hover`) will make it so the transition affects when you hover _on_ and _off_ of the button

I'd still like to put together some design resources for everyone, I just haven't found the time yet. Keep up the good work!

**Comment by copyrighthero** [comment]
@stuartpearman ,

Thank you very much for the resource, advice and kind words :-) I'm definitely going to check out the guidline :-)

Thank you and ave a good day!

Hansheng
